//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsSet
    {
        public int Id { get; set; }
        public string FirserName { get; set; }
        public string MiddleName { get; set; }
        public string lastName { get; set; }
        public string Phome { get; set; }
        public string Email { get; set; }
    }
}
